# permissions for end users to edit clusterpolicysets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8lex
    app.kubernetes.io/managed-by: kustomize
  name: clusterpolicyset-clusterpolicyset-editor-role
rules:
- apiGroups:
  - clusterpolicyset.k8lex.io
  resources:
  - clusterpolicysets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterpolicyset.k8lex.io
  resources:
  - clusterpolicysets/status
  verbs:
  - get
