# permissions for end users to edit clusterpolicynotifiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8lex
    app.kubernetes.io/managed-by: kustomize
  name: clusterpolicynotifier-clusterpolicynotifier-editor-role
rules:
- apiGroups:
  - clusterpolicynotifier.k8lex.io
  resources:
  - clusterpolicynotifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterpolicynotifier.k8lex.io
  resources:
  - clusterpolicynotifiers/status
  verbs:
  - get
