# permissions for end users to view clusterpolicyvalidators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8lex
    app.kubernetes.io/managed-by: kustomize
  name: clusterpolicyvalidator-viewer-role
rules:
- apiGroups:
  - policies.k8lex.io
  resources:
  - clusterpolicyvalidators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policies.k8lex.io
  resources:
  - clusterpolicyvalidators/status
  verbs:
  - get
