# This rule is not used by the project k8lex itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to clusterpolicyupdater.k8lex.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8lex
    app.kubernetes.io/managed-by: kustomize
  name: clusterpolicyupdater-clusterpolicyupdater-viewer-role
rules:
- apiGroups:
  - clusterpolicyupdater.k8lex.io
  resources:
  - clusterpolicyupdaters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clusterpolicyupdater.k8lex.io
  resources:
  - clusterpolicyupdaters/status
  verbs:
  - get
