# permissions for end users to edit notifiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8lex
    app.kubernetes.io/managed-by: kustomize
  name: notifications-notifier-editor-role
rules:
- apiGroups:
  - notifications.k8lex.io
  resources:
  - notifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notifications.k8lex.io
  resources:
  - notifiers/status
  verbs:
  - get
