---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterpolicyupdater.k8lex.io
  resources:
  - clusterpolicyupdaters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterpolicyupdater.k8lex.io
  resources:
  - clusterpolicyupdaters/finalizers
  verbs:
  - update
- apiGroups:
  - clusterpolicyupdater.k8lex.io
  resources:
  - clusterpolicyupdaters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policies.example.com
  resources:
  - clusterpolicynotifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policies.example.com
  resources:
  - clusterpolicynotifiers/finalizers
  verbs:
  - update
- apiGroups:
  - policies.example.com
  resources:
  - clusterpolicynotifiers/status
  verbs:
  - get
  - patch
  - update
