apiVersion: policies.example.com/v1alpha1
kind: ClusterPolicyValidator
metadata:
  name: no-latest-image-validator
spec:
  description: "Validates that container images do not use the 'latest' tag."
  validationRules:
    - name: "no-latest-tag"
      description: "Checks that images do not use the 'latest' tag."
      severity: "High"
      namespaceSelector:
        matchNames:
          - default
      labelSelector:
        matchLabels:
          app: myapp
      matchResources:
        kinds:
          - Pod
      conditions:
        - key: spec.containers[*].image
          operator: "NotIn"
          values:
            - "latest"
      action: "Block"  # block | warn | continue
  notification:
    enabled: true  # Global notification setting
    notifierRef:
      name: my-notifier
      namespace: default
