## Append samples of your project ##
resources:
- clusterpolicyvalidator_v1alpha1_clusterpolicyvalidator.yaml
- clusterpolicyupdater_v1alpha1_clusterpolicyupdater.yaml
- clusterpolicyset_v1alpha1_clusterpolicyset.yaml
- clusterpolicynotifier_v1alpha1_clusterpolicynotifier.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
