apiVersion: notifications.k8lex.io/v1alpha1
kind: Notifier
metadata:
  labels:
    app.kubernetes.io/name: k8lex
    app.kubernetes.io/managed-by: kustomize
  name: notifier-sample
spec:
  # TODO(user): Add fields here
