apiVersion: clusterpolicyvalidator.k8lex.io/v1alpha1
kind: ClusterPolicyValidator
metadata:
  name: no-latest-image-validator
  namespace: k8lex
spec:
  description: "Validates that images do not use the 'latest' tag."
  namespaces:
    include:
      - k8lex
  validationRules:
    - name: "no-latest-tag"
      description: "Checks that images do not use the 'latest' tag."
      severity: "High"
      errorMessage: "The resource must not use the 'latest' tag for the image."
      matchResources:
        kinds:
          - Pod
          - Deployment 
      conditions:
        # For Deployments, use the correct path
        - key: spec.template.spec.containers[*].image
          operator: "Contains"
          values:
            - ":latest"
      action: "block"  # Note: lowercase 'block'
  notification:
    enabled: false