# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/clusterpolicyvalidator.k8lex.io_clusterpolicyvalidators.yaml
- bases/clusterpolicyupdater.k8lex.io_clusterpolicyupdaters.yaml
- bases/clusterpolicyset.k8lex.io_clusterpolicysets.yaml
- bases/clusterpolicynotifier.k8lex.io_clusterpolicynotifiers.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_clusterpolicyvalidator_clusterpolicyvalidators.yaml
#- path: patches/cainjection_in_clusterpolicyupdater_clusterpolicyupdaters.yaml
#- path: patches/cainjection_in_clusterpolicyset_clusterpolicysets.yaml
#- path: patches/cainjection_in_clusterpolicynotifier_clusterpolicynotifiers.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

#configurations:
#- kustomizeconfig.yaml
